
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================
//Lab2, simple ripple carry adder.
module top(

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [3:0]		SW,
	
	output			  [1:0]     coo
);



//=======================================================
//  REG/WIRE declarations
//=======================================================


wire [3:0] sumWire, sumWire1;


//=======================================================
//  Structural coding
//=======================================================

 

add4bit bit4_0(
 .a(SW),
 .b(4'b0000),
 .ci(1'b0),
 .s(sumWire),
 .co(coo[0])
 
 );
add4bit bit4_1(
 .a(SW),
 .b(4'b0001),
 .ci(1'b0),
 .s(sumWire1),
 .co(coo[1])
 
 );

 seg7 u_0(
 .bit4(sumWire),
 .hexOutput(HEX0)
 );

 seg7 u_1(
 .bit4(sumWire1),
 .hexOutput(HEX1)
 );
 
 assign HEX2 = 8'b11111111;
 assign HEX3 = 8'b11111111;
 assign HEX4 = 8'b11111111;
 assign HEX5 = 8'b11111111;
endmodule
