//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================
//Tests the acceleromoter on the DE-10 Lite board and moves the LED along, as it shows its position on the HEX displays
module top(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// Accelerometer //////////
	output		          		GSENSOR_CS_N,
	input 		     [2:1]		GSENSOR_INT,
	output		          		GSENSOR_SCLK,
	inout 		          		GSENSOR_SDI,
	inout 		          		GSENSOR_SDO
);

reg [9:0] twosCompNum;
reg nothing;
reg outofrange;

initial begin
	twosCompNum = 10'b0000000000;
	nothing = 1'b0;
	outofrange = 1'b0;
end

pll	pll_inst (
	.inclk0 ( MAX10_CLK1_50 ),
	.c0 ( c0_sig ),
	.c1 ( c1_sig ),
	.c2 ( c2_sig )

	);

spi_control spi_control_inst(
	.clk (c0_sig),
	.spi_clk(c1_sig),
	.spi_clk_out(c2_sig)
	);

BCDConverter BCDConverter_inst(
	.twosCompNum(10'b1000000111),
	.nothing(1'b0),
	.outofrange(1'b0),
	.out0(HEX0),
	.out1(HEX1),
	.out2(HEX2),
	.out3(HEX3)
);

//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================



endmodule
